language: python

python:
 - "3.6.8"

install:
 - python -m pip install flake8

script: 
  - python3 test_unitaire.py
  - flake8 test_unitaire.py --count --select=E9,F63,F7,F82 --show-source --statistics
  - flake8 test_unitaire.py --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
